// Code generated by Slice Machine. DO NOT EDIT.

import HeroSlice from './HeroSlice';
import Post from './Post';

export {
	HeroSlice,
	Post,
};

export const components = {
	hero_slice: HeroSlice,
	blog_post: Post,
};
